---
title: "Cox-Ingersoll-Ross (CIR) model"
author: "Quasar"
date: "2024-05-08"
categories: [cox-ingersoll-ross-model,interest-rate-modelling]      
toc: true
toc-depth: 3
---

The short rate under the CIR model has the dynamics:

$$dr_t = \kappa (\theta - r_t)dt + \sigma \sqrt{r_t}dB_t$$

For a moment, if we drop the stochastic term, and merely consider the first order linear ODE $\frac{dr_t}{dt} + \kappa r_t = \kappa \theta$, the integrating factor for this differential equation is $e^{\int \kappa dt} = e^{\kappa t}$. Multiplying both sides by the integrating factor, we have:

\begin{align*}
e^{\kappa t} dr_t &= \kappa(\theta - r_t) e^{\kappa t}dt + \sigma e^{\kappa t}\sqrt{r_t} dB_t \\
e^{\kappa t} dr_t + r_t e^{\kappa t}dt &= \kappa e^{\kappa t}\theta dt + \sigma e^{\kappa t}\sqrt{r_t} dB_t \\
d(e^{\kappa t} r_t) &= \kappa e^{\kappa t}\theta dt + \sigma e^{\kappa t}\sqrt{r_t} dB_t \\
\int_{0}^{t} d(e^{\kappa s} r_s) &= \theta \kappa\int_{0}^{t}  e^{\kappa s} ds + \sigma \int_{0}^{t}  e^{\kappa s}\sqrt{r_s} dB_s \\
[e^{\kappa s} r_s]_{0}^{t} &= \kappa \theta \left[\frac{e^{\kappa s}}{\kappa}\right]_{0}^{t} + \sigma \int_{0}^{t}  e^{\kappa s}\sqrt{r_s} dB_s\\
e^{\kappa t}r_t - r_0 &= \theta (e^{\kappa t} - 1) + \sigma \int_{0}^{t}  e^{\kappa s}\sqrt{r_s} dB_s \\
e^{\kappa t} r_t &= r_0 + \theta (e^{\kappa t} - 1) + \sigma \int_{0}^{t}  e^{\kappa s}\sqrt{r_s} dB_s \\
r_t &= r_0 e^{-\kappa t} + \theta (1 - e^{-\kappa t}) + \sigma \int_{0}^{t}  e^{-\kappa (t-s)}\sqrt{r_s} dB_s 
\end{align*}

The mean is given by:

\begin{align*}
\mathbf{E}[r_t] &= r_0 e^{-\kappa t} + \theta (1 - e^{-\kappa t})
\end{align*}

The random variable $\sigma \int_{0}^{t}  e^{-\kappa (t-s)}\sqrt{r_s} dB_s$ has mean $0$ and variance:

\begin{align*}
\mathbf{E}\left[\left(\sigma \int_{0}^{t}  e^{-\kappa (t-s)}\sqrt{r_s} dB_s\right)^2\right] &= \sigma^2 \int_{0}^{t}e^{-2\kappa(t-s)} \mathbf{E}[r_s] ds \\
&= \sigma^2 e^{-2\kappa t}\int_{0}^{t}e^{2\kappa s} \left(r_0 e^{-\kappa s} + \theta(1-e^{-\kappa s})\right) ds\\
&= \sigma^2 r_0 e^{-2\kappa t} \int_{0}^{t} e^{\kappa s} ds + \sigma^2 \theta e^{-2\kappa t} \int_{0}^{t}(e^{2\kappa s}-e^{\kappa s}) ds \\
&= \sigma^2 r_0 e^{-2\kappa t} \left[\frac{e^{\kappa s}}{\kappa} \right]_{0}^{t} +\sigma^2 \theta e^{-2\kappa t} \left[\frac{e^{2\kappa s}}{2\kappa} - \frac{e^{\kappa s}}{\kappa}\right]_{0}^{t}\\
&= \frac{\sigma^2 r_0}{\kappa} e^{-2\kappa t} (e^{\kappa t} - 1)+\sigma^2 \theta e^{-2\kappa t} \left[\frac{e^{2\kappa s}}{2\kappa} - \frac{2e^{\kappa s}}{2\kappa}\right]_{0}^{t}\\
&= \frac{\sigma^2 r_0}{\kappa} e^{-2\kappa t}(e^{\kappa t} - 1)+\frac{\sigma^2 \theta}{2\kappa} e^{-2\kappa t}(e^{2\kappa t} - 2e^{\kappa t} - (1 - 2))\\
&= \frac{\sigma^2 r_0}{\kappa} e^{-2\kappa t}(e^{\kappa t} - 1)+\frac{\sigma^2 \theta}{2\kappa}e^{-2\kappa t} (1 + e^{2\kappa t} - 2e^{\kappa t})\\
&= \frac{\sigma^2 r_0}{\kappa} (e^{-\kappa t} - e^{-2\kappa t})+\frac{\sigma^2 \theta}{2\kappa} (1 - e^{-\kappa t})^2
\end{align*}






