---
title: "`flat_map` internals"
author: "`dev::author`"
date: "2026-08-30"
categories: [C++]
toc: true
toc-depth: 3
filters:
   - include-code-files
---

# Introduction

We use hash-tables a lot in software programming and there has been a strong desire for a more space and run-time efficient representation of a `map` among C++ users. I recently watched Matt Kulukundis' CppCon 2017 talk, [Designing a fast, efficient, cache-friendly hash Table, step by step](https://www.youtube.com/watch?v=ncHmEUmJZf4). In this blog-post, I would like to explore the implementation details of the abseil library's `flat_hash_map` data-structure. 

```{python}
%load_ext itikz
```


# The standard library's `unordered_set` 

Our starting point is the standard library's implementation of a hash-table called the `unordered_set`. Here, we have a table(array) `S`, of size $2^n$. The array elements $S[0],\ldots,S[2^n - 1]$ are called slots. A new element is inserted into the table by hashing it, to find the correct slot. The element is stored at `hash(item) % capacity()` index. Two elements with the same hash-code, would have to be stored at the same slot; so we need a way to resolve collisions. `unordered_set` uses chaining, so each slot `S[i]` is more like a bucket, it is a linked-list of all items that hash to the same hash-code.

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "The unordered_set"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \draw[fill=white!91!blue!90!cyan] (0,3) rectangle (0.3,0);
  \draw (0,2.25) -- (0.3,2.25);
  \draw (0,1.5) -- (0.3,1.5);
  \draw (0,1.25) -- (0.3,1.25);
  \draw (0,1) -- (0.3,1);
  \draw (0,0.25) -- (0.3,0.25);
  \draw[fill=pink] (0,2.75) rectangle (0.3,2.49);
  \draw[fill=pink] (1,2.75) rectangle (1.3,2.49);
  \draw[fill=pink] (1.3,2.75) rectangle (1.6,2.49);
  \draw[fill=pink] (1.6,2.75) rectangle (1.9,2.49);
  \draw[fill=pink] (2.3,2.75) rectangle (2.6,2.49);
  \draw[fill=pink] (2.6,2.75) rectangle (2.9,2.49);
  \draw[fill=pink] (2.9,2.75) rectangle (3.2,2.49);
  \draw[fill=yellow!30] (0,2) rectangle (0.3,1.74);
  \draw[fill=yellow!30] (1,2) rectangle (1.3,1.74);
  \draw[fill=yellow!30] (1.3,2) rectangle (1.6,1.74);
  \draw[fill=yellow!30] (1.6,2) rectangle (1.9,1.74);
  \draw[fill=green!30] (0,0.73) rectangle (0.3,0.47);
  \draw[fill=green!30] (1,0.73) rectangle (1.3,0.47);
  \draw[fill=green!30] (1.3,0.73) rectangle (1.6,0.47);
  \draw[fill=green!30] (1.6,0.73) rectangle (1.9,0.47);
  \draw[fill=green!30] (2.3,0.73) rectangle (2.6,0.47);
  \draw[fill=green!30] (2.6,0.73) rectangle (2.9,0.47);
  \draw[fill=green!30] (2.9,0.73) rectangle (3.2,0.47);
  \draw[fill=green!30] (3.7,0.73) rectangle (4,0.47);
  \draw[fill=green!30] (4,0.73) rectangle (4.3,0.47);
  \draw[fill=green!30] (4.3,0.73) rectangle (4.6,0.47);
  \draw[arrows=-Latex] (0.15,2.6) -- (1.05,2.6);
  \draw[arrows=-Latex] (0.16,1.86) -- (1.06,1.86);
  \draw[arrows=-Latex] (0.15,0.58) -- (1.05,0.58);
  \node[draw=none, node font=\small] at (0.15,3.33) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] at (1.15,2.6) {H};
  \node[draw=none, node font=\small] at (3.06,2.62) {$\phi$};
  \node[draw=none, node font=\small] at (4.45,0.59) {$\phi$};
  \node[draw=none, node font=\small] at (1.74,1.88) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.15,1.86) {H};
  \node[draw=none, node font=\ttfamily] at (1.15,0.61) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (2.45,2.62) {H};
  \draw[arrows=-Latex] (1.72,2.61) -- (2.36,2.62);
  \draw[arrows=-Latex] (1.69,0.6) -- (2.33,0.61);
  \draw[arrows=-Latex] (3.07,0.58) -- (3.71,0.59);
  \node[draw=none, node font=\ttfamily] at (2.47,0.59) {H};
  \node[draw=none, node font=\ttfamily] at (3.86,0.6) {H};
  \node[draw=none, node font=\ttfamily] at (1.45,2.61) {V};
  \node[draw=none, node font=\ttfamily] at (1.46,1.85) {V};
  \node[draw=none, node font=\ttfamily] at (1.46,0.6) {V};
  \node[draw=none, node font=\ttfamily] at (2.75,2.61) {V};
  \node[draw=none, node font=\ttfamily] (node2) at (2.75,0.58) {V};
  \node[draw=none, node font=\ttfamily] at (4.15,0.6) {V};
  \draw (1.46,0.91) -- (2.8,1.4);
  \draw (2.66,0.9) -- (2.8,1.4);

  \draw (4.15,0.8) -- (2.8,1.4);
  \node[draw=none, node font=\small] at (2.89,1.58) {Bucket chain};
\end{tikzpicture}
```

The `H` in the diagram is the *hash-code*. It is `64`-bits. `V` is the actual value - the thing that we want to store. Because, each item lives in a separate node, different from the primary data-structure - the bucket array `S`, we say it has pointer-stability. No matter, what happens to the internals of the hash-table, the value doesn't move, it lives at the same memory address. This is a property guaranteed by the standard. $\phi$ denotes `nullptr`; it is used to indicate the end of linked-lists. The green nodes are all in the same bucket chain. 

The above mental picture is ballpark correct. The actual picture is more like this:

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "More realistic implementation details of unordered_set"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \draw[fill=white!91!blue!90!cyan] (0,3) rectangle (0.3,0);
  \draw (0,2.25) -- (0.3,2.25);
  \draw (0,1.5) -- (0.3,1.5);
  \draw (0,1.25) -- (0.3,1.25);
  \draw (0,1) -- (0.3,1);
  \draw (0,0.25) -- (0.3,0.25);
  \draw[fill=pink] (0,2.75) rectangle (0.3,2.49);
  \draw[fill=pink] (1,2.75) rectangle (1.3,2.49);
  \draw[fill=pink] (1.3,2.75) rectangle (1.6,2.49);
  \draw[fill=pink] (1.6,2.75) rectangle (1.9,2.49);
  \draw[fill=pink] (2.3,2.75) rectangle (2.6,2.49);
  \draw[fill=pink] (2.6,2.75) rectangle (2.9,2.49);
  \draw[fill=pink] (2.9,2.75) rectangle (3.2,2.49);
  \draw[fill=yellow!30] (0,2) rectangle (0.3,1.74);
  \draw[fill=yellow!30] (1,2) rectangle (1.3,1.74);
  \draw[fill=yellow!30] (1.3,2) rectangle (1.6,1.74);
  \draw[fill=yellow!30] (1.6,2) rectangle (1.9,1.74);
  \draw[fill=green!30] (0,0.73) rectangle (0.3,0.47);
  \draw[fill=green!30] (1,0.73) rectangle (1.3,0.47);
  \draw[fill=green!30] (1.3,0.73) rectangle (1.6,0.47);
  \draw[fill=green!30] (1.6,0.73) rectangle (1.9,0.47);
  \draw[fill=green!30] (2.3,0.73) rectangle (2.6,0.47);
  \draw[fill=green!30] (2.6,0.73) rectangle (2.9,0.47);
  \draw[fill=green!30] (2.9,0.73) rectangle (3.2,0.47);
  \draw[fill=green!30] (3.7,0.73) rectangle (4,0.47);
  \draw[fill=green!30] (4,0.73) rectangle (4.3,0.47);
  \draw[fill=green!30] (4.3,0.73) rectangle (4.6,0.47);
  \node[draw=none, node font=\small] at (0.15,3.76) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node6) at (1.15,2.6) {H};
  \node[draw=none, node font=\small] at (4.45,0.59) {$\phi$};
  \node[draw=none, node font=\ttfamily] (node5) at (1.15,1.86) {H};
  \node[draw=none, node font=\ttfamily] (node8) at (1.15,0.61) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (2.45,2.62) {H};
  \draw[arrows=-Latex] (1.72,2.61) -- (2.36,2.62);
  \draw[arrows=-Latex] (1.69,0.6) -- (2.33,0.61);
  \draw[arrows=-Latex] (3.07,0.58) -- (3.71,0.59);
  \node[draw=none, node font=\ttfamily] at (2.47,0.59) {H};
  \node[draw=none, node font=\ttfamily] at (3.86,0.6) {H};
  \node[draw=none, node font=\ttfamily] (node4) at (1.45,2.61) {V};
  \node[draw=none, node font=\ttfamily] (node9) at (1.46,1.85) {V};
  \node[draw=none, node font=\ttfamily] at (1.46,0.6) {V};
  \node[draw=none, node font=\ttfamily] (node7) at (2.75,2.61) {V};
  \node[draw=none, node font=\ttfamily] (node2) at (2.75,0.58) {V};
  \node[draw=none, node font=\ttfamily] at (4.15,0.6) {V};
  \draw (1.46,0.91) -- (2.8,1.4);
  \draw (2.66,0.9) -- (2.8,1.4);

  \draw (4.15,0.8) -- (2.8,1.4);
  \node[draw=none, node font=\small] at (2.89,1.58) {Bucket chain};
  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-0.68,3.25) {head};
  \draw[arrows=Circle-Latex] (0.2,2.65) .. controls (-0.87,2.25) and (-0.77,2.8) .. (-0.82,3.02);
  \draw[arrows=Circle-Latex] (node3.east) .. controls (0.3,3.48) and (0.92,3.5) .. (1.12,2.76);

  \draw[arrows=Circle-Latex] (0.1,1.84) .. controls (0.57,2.5) and (1.37,1.85) .. (2.36,2.49);

  \draw[arrows=Circle-Latex] (3.05,2.62) .. controls (3.7,2.31) and (2.5,2.39) .. (1.9,2);

  \draw[arrows=Circle-Latex] (0.15,0.55) .. controls (1,1) and (0.3,1.58) .. (node5.west);

  \draw[arrows=Circle-Latex] (1.73,1.9) .. controls (1.4,0.73) and (0.18,1.08) .. (1,0.5);
\end{tikzpicture}
```

If we zoom out and think for a bit, it makes more sense, why it is implemnented like this. Let's rearrange the above picture. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "Implementation details of unordered_set"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \draw[fill=yellow!30] (1.24,1.15) rectangle (1.54,0.89);
  \draw[fill=yellow!30] (1.54,1.15) rectangle (1.84,0.89);
  \draw[fill=yellow!30] (1.84,1.15) rectangle (2.14,0.89);
  \draw[fill=green!30] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (2.6,1.13) rectangle (2.9,0.87);
  \draw[fill=green!30] (2.9,1.13) rectangle (3.2,0.87);
  \draw[fill=green!30] (3.2,1.13) rectangle (3.5,0.87);
  \draw[fill=green!30] (3.9,1.13) rectangle (4.2,0.87);
  \draw[fill=green!30] (4.2,1.13) rectangle (4.5,0.87);
  \draw[fill=green!30] (4.5,1.13) rectangle (4.8,0.87);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.55) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.01) {H};
  \node[draw=none, node font=\ttfamily] at (2.75,1.01) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily] at (4.07,0.99) {H};
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily] at (1.7,1) {V};
  \node[draw=none, node font=\ttfamily] at (3.06,1) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily] (node2) at (4.35,0.98) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};


  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);
\end{tikzpicture}
```

Now, if we look more closely, we are storing both the hash-codes and pointers for each element. That's an extra `16`-bytes per entry. When we iterate across the `unordered_set`, we actually end up walking this linked-list. That takes $O(\texttt{size})$ runtime. The iteration order of this container is reproducible, for a given insertion order. 

## How does `.find(val)` operate on this table?

We want to find the element highlighted in red; it happens to be the second element in the bucket chain. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: ".find(val) operation"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \draw[fill=yellow!30] (1.24,1.15) rectangle (1.54,0.89);
  \draw[fill=yellow!30] (1.54,1.15) rectangle (1.84,0.89);
  \draw[fill=yellow!30] (1.84,1.15) rectangle (2.14,0.89);
  \draw[fill=green!30] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (2.6,1.13) rectangle (2.9,0.87);
  \draw[fill=green!30] (2.9,1.13) rectangle (3.2,0.87);
  \draw[fill=green!30] (3.2,1.13) rectangle (3.5,0.87);
  \draw[fill=green!30] (3.9,1.13) rectangle (4.2,0.87);
  \draw[fill=green!30] (4.2,1.13) rectangle (4.5,0.87);
  \draw[fill=green!30] (4.5,1.13) rectangle (4.8,0.87);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.55) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.01) {H};
  \node[draw=none, node font=\ttfamily] at (2.75,1.01) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily, text=red] at (4.07,0.99) {H};
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily] at (1.7,1) {V};
  \node[draw=none, node font=\ttfamily] at (3.06,1) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily, text=red] (node2) at (4.35,0.98) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};


  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);
\end{tikzpicture}
```

We compute the `hash(val) % capacity()` to figure out the slot in the bucket array. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "Compute hash(val) to figure out the bucket"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \draw[fill=yellow!30] (1.24,1.15) rectangle (1.54,0.89);
  \draw[fill=yellow!30] (1.54,1.15) rectangle (1.84,0.89);
  \draw[fill=yellow!30] (1.84,1.15) rectangle (2.14,0.89);
  \fill[green!30, draw=blue, ultra thick] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (2.6,1.13) rectangle (2.9,0.87);
  \draw[fill=green!30] (2.9,1.13) rectangle (3.2,0.87);
  \draw[fill=green!30] (3.2,1.13) rectangle (3.5,0.87);
  \draw[fill=green!30] (3.9,1.13) rectangle (4.2,0.87);
  \draw[fill=green!30] (4.2,1.13) rectangle (4.5,0.87);
  \draw[fill=green!30] (4.5,1.13) rectangle (4.8,0.87);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.56) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.01) {H};
  \node[draw=none, node font=\ttfamily] at (2.75,1.01) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily, text=red] at (4.07,0.99) {H};
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily] at (1.7,1) {V};
  \node[draw=none, node font=\ttfamily] at (3.06,1) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily, text=red] (node2) at (4.35,0.98) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};


  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);
\end{tikzpicture}
```

We follow that to the entry before the first entry in the green bucket chain. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "Jump to the entry before the first entry in the green bucket chain"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \fill[yellow!30, draw=blue, ultra thick] (1.24,1.15) rectangle (2.12,0.89);
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \fill[green!30, draw=blue, very thick] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (2.6,1.13) rectangle (2.9,0.87);
  \draw[fill=green!30] (2.9,1.13) rectangle (3.2,0.87);
  \draw[fill=green!30] (3.2,1.13) rectangle (3.5,0.87);
  \draw[fill=green!30] (3.9,1.13) rectangle (4.2,0.87);
  \draw[fill=green!30] (4.2,1.13) rectangle (4.5,0.87);
  \draw[fill=green!30] (4.5,1.13) rectangle (4.8,0.87);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.56) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.02) {H};
  \node[draw=none, node font=\ttfamily] at (2.75,1.01) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily, text=red] at (4.07,0.99) {H};
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily, minimum width=8pt] (node6) at (1.68,1.01) {V};
  \node[draw=none, node font=\ttfamily] at (3.06,1) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily, text=red] (node2) at (4.35,0.98) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};
  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);

  \draw (1.88,1.12) -- (1.88,0.92);\draw (1.53,1.12) -- (1.53,0.92);
\end{tikzpicture}
```

We always just skip this one. Then, we go to the first entry that's actually there. We compare the computed hash `hash(val)` against the hash stored in the node. If that matches, we compare the value `V` against the value that we want. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "Jump to the first entry in bucket chain, compare the hash code and the value against what we want"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \fill[yellow!30, draw=blue, ultra thick] (1.24,1.15) rectangle (2.12,0.89);
  \fill[fill=green!30, draw=blue, ultra thick] (2.57,1.13) rectangle (3.44,0.87);
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \fill[green!30, draw=blue, very thick] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (3.9,1.13) rectangle (4.2,0.87);
  \draw[fill=green!30] (4.2,1.13) rectangle (4.5,0.87);
  \draw[fill=green!30] (4.5,1.13) rectangle (4.8,0.87);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.56) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.02) {H};
  \node[draw=none, node font=\ttfamily] at (2.73,1) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily, text=red] at (4.07,0.99) {H};
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily, minimum width=8pt] (node6) at (1.68,1.01) {V};
  \node[draw=none, node font=\ttfamily] at (2.99,0.99) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily, text=red] (node2) at (4.35,0.98) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};
  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);

  \draw (1.88,1.12) -- (1.88,0.92);
  \draw (2.85,1.1) -- (2.85,0.9);
  \draw (3.14,1.1) -- (3.14,0.9);\draw (1.53,1.12) -- (1.53,0.92);
\end{tikzpicture}
```

In our case, we jump to the next node, because it didn't match. Now, we actually get to the one we want. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "Jump to the second entry, which matches against what we want."
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5,transform shape]
  \pagecolor{white}
  \fill[yellow!30, draw=blue, ultra thick] (1.24,1.15) rectangle (2.12,0.89);
  \fill[fill=green!30, draw=blue, ultra thick] (2.57,1.13) rectangle (3.44,0.87);
  \draw[fill=white!91!blue!90!cyan, rotate=90] (-0.3,1.1) rectangle (0,-2.46);
  \draw (-0.2,0) -- (-0.2,-0.3);
  \draw (0.7,0) -- (0.7,-0.3);
  \draw (0.99,0) -- (0.99,-0.3);
  \draw (1.3,0) -- (1.3,-0.3);
  \draw (2.12,0) -- (2.12,-0.3);
  \draw[fill=pink] (-0.8,0) rectangle (-0.48,-0.3);
  \draw[fill=pink] (-1.42,1.13) rectangle (-1.12,0.87);
  \draw[fill=pink] (-1.12,1.13) rectangle (-0.8,0.87);
  \draw[fill=pink] (-0.8,1.13) rectangle (-0.51,0.87);
  \draw[fill=pink] (-0.09,1.13) rectangle (0.21,0.87);
  \draw[fill=pink] (0.21,1.13) rectangle (0.51,0.87);
  \draw[fill=pink] (0.51,1.13) rectangle (0.81,0.87);
  \draw[fill=yellow!30] (0.1,0) rectangle (0.41,-0.3);
  \fill[green!30, draw=blue, very thick] (1.56,0) rectangle (1.82,-0.3);
  \draw[fill=green!30] (5.3,1.13) rectangle (5.6,0.87);
  \draw[fill=green!30] (5.6,1.13) rectangle (5.9,0.87);
  \draw[fill=green!30] (5.9,1.13) rectangle (6.2,0.87);
  \node[draw=none, node font=\small] at (0.72,-0.56) {$S[0,...,2^n-1]$};
  \node[draw=none, node font=\ttfamily] (node4) at (-1.28,0.98) {H};
  \node[draw=none, node font=\small] at (6.05,0.99) {$\phi$};
  \node[draw=none, node font=\ttfamily] at (1.39,1.02) {H};
  \node[draw=none, node font=\ttfamily] at (2.73,1) {H};
  \node[draw=none, node font=\ttfamily] (node1) at (0.05,1) {H};
  \draw[arrows=-Latex] (-0.69,0.99) -- (-0.04,1);
  \draw[arrows=-Latex] (-2.09,0.99) -- (-1.44,1);
  \draw[arrows=-Latex] (0.63,0.99) -- (1.28,1);
  \draw[arrows=-Latex] (1.96,1) -- (2.61,1.01);
  \draw[arrows=-Latex] (3.29,1) -- (3.93,1.01);
  \draw[arrows=-Latex] (4.67,0.98) -- (5.31,0.99);
  \node[draw=none, node font=\ttfamily] at (5.46,1) {H};
  \node[draw=none, node font=\ttfamily] at (-0.97,0.99) {V};
  \node[draw=none, node font=\ttfamily, minimum width=8pt] (node6) at (1.68,1.01) {V};
  \node[draw=none, node font=\ttfamily] at (2.99,0.99) {V};
  \node[draw=none, node font=\ttfamily] (node5) at (0.36,0.99) {V};
  \node[draw=none, node font=\ttfamily] at (5.75,1) {V};
  \node[draw, node font=\small, fill=white!97!blue!88!cyan] (node3) at (-2.5,0.98) {head};
  \draw[arrows=-Latex] (-0.66,-0.15) -- (node3.south);
  \draw[arrows=-Latex] (0.26,-0.15) -- (-0.09,0.89);
  \draw[arrows=-Latex] (1.71,-0.15) -- (1.36,0.89);
  \draw (1.88,1.12) -- (1.88,0.92);
  \draw (2.85,1.1) -- (2.85,0.9);
  \draw (3.14,1.1) -- (3.14,0.9);
  \fill[fill=green!30, draw=blue, ultra thick] (3.92,1.16) rectangle (4.78,0.9);
  \draw (4.2,1.13) -- (4.2,0.93);
  \draw (4.49,1.13) -- (4.49,0.93);
  \draw (1.53,1.12) -- (1.53,0.92);
  \node[draw=none, node font=\ttfamily, text=red] (node2) at (4.35,1.02) {V};
  \node[draw=none, node font=\ttfamily, text=red] at (4.09,1.03) {H};
\end{tikzpicture}
```

This required $4$ different memory accesses to find the element highlighted in red. In performance-terms, this is costly, because these nodes might not even be in L1d cache, and every cache miss is expensive. We now have a rough idea of how bucket-chaining hash tables work. 

# `absl::flat_hash_map` high-level design

The `absl::flat_hash_map` directly stores the `value_type` inside the container's main array to avoid memory indirections. Because they move data when they rehash, elements do not get pointer stability compared to node-based associative containers like `std::unordered_map`. 

A nice summary of some of the tradeoffs between node-based and flat associative containers is given in the Boost documentation:

- Faster lookup than the standard(node-based) associative containers.

- Much faster iteration than the standard(node-based) associative containers.

- Less memory consumption for each element. 

- Improved cache performance (as data is stored contiguously in memory).

- Slower insertion and erasure the standard associative containers.

`absl::flat_hash_map` holds a densely packed array of metadata, containing presence information for entries in the hash table. An extra `1`-byte of meta-data is stored in the control bytes array per entry in the main array. The array of meta-data and the main array are parallel arrays. 

## `flat_hash_map` inheritance hierarchy

The `flat_hash_map` is a class template with the key type `typename K` ,the value type `typename V`, the hash-function `typename Hash`, the equality comparison operator `typename Eq`, the allocator type `Allocator` as template parameters. `flat_hash_map` inherits from a base class which is derived as follows. 

```{.cpp include="./flat_hash_map.h" start-line=139 end-line=149 code-line-numbers="true" filename="absl/container/flat_hash_map.h"}
```

`absl::container_internal::InstantiateRawHashMap` is like a type metafunction that accepts `4` types as inputs: the `Policy`, the hash functor type `Hash`, the equality comparison operator type `Eq` and the allocator type `Alloc` and returns a concrete type that serves as the base-class for `flat_hash_map`.

```{.cpp include="./raw_hash_map.h" start-line=34 end-line=44 code-line-numbers="true" filename="absl/container/internal/raw_hash_map.h"}
```

It internally calls another meta-function `ApplyWithoutDefaultSuffix` with the types `raw_hash_map`, a list of types `TypeList<int, Policy::DefaultHash, Policy::DefaultEq, Policy::DefaultAlloc>`, a second list of types `TypeList<Policy, Hash, Eq, Alloc>`. 

```{.cpp include="./common.h" start-line=279 end-line=294 code-line-numbers="true" filename="absl/container/internal/common.h"}
```

`ApplyWithoutDefaultSuffix` is another metafunction. Given two typelists - a default list: `TypeList<D, Ds...>` and list of `T`s: `<TypeList<T, Ts...>>`, it tests if the two typelists are different (observe that we have `!std::is_same_v<T1,T2>`), and recursively calls itself, passing the arguments i) tail of the default typelist ii) the tail `TypeList<Ts...> iii) a third typelist which is used to accumulate `T`. As we walk through the two type-lists in lock-step fashion, each `T` gets appended to the list of types accumulated so far on line 296 as `TypeList<L..., T>`. 

At the point, when the reduced typelists have an identical tail, the recursion stops. Recall that, `std::enable_if_t<Predicate, T = void>` returns `T` if the `Predicate` evaluates to `std::true_type`, otherwise it fails. Because of SFINAE(substitution failure is not an error), this does not mean a compile-time error. Effectively, `ApplyWithoutDefaultSuffix<Template, TypeList<D1,D2,D3,T4>, TypeList<T1,T2,T3,D4>>` evaluates to `Template<T1,T2,T3>`. The comments on lines 282-284 also elucidate this point.  

The `ApplyWithoutDefaultSuffix` metafunction returns the type `L::Apply<Template>` on line 288. 

Since `L` is a `TypeList<T1,T2,T3>`, this simply evaluates to `Template<T...>` or `Template<T1,T2,T3>`. 

```{.cpp include="./common.h" start-line=272 end-line=276 code-line-numbers="true" filename="absl/container/internal/common.h"}
```

To summarize, therefore, `flat_hash_map` inherits from `raw_hash_map<Policy, Traits...>` where we use the user-supplied policy traits: the hash-function, equality and allocator as long as they differ from the default policy.

```{.cpp include="./flat_hash_map.h" start-line=139 end-line=149 code-line-numbers="true" filename="absl/container/flat_hash_map.h"}
```

The `raw_hash_map` type in turn inherits from `raw_hash_set`.

```{.cpp include="./raw_hash_map.h" start-line=46 end-line=47 code-line-numbers="true" filename="absl/container/internal/raw_hash_map.h"}
```

# The `raw_hash_set` data structure

The `raw_hash_set` data-structure is a `Compressedtuple` of `CommonFields`, `hasher`, `key_equal` and `CharAlloc` types.

```cpp
struct raw_hash_set{
  // ...
  absl::container_internal::CompressedTuple<
  CommonFields, hasher, key_equal,CharAlloc>
      settings_{
        CommonFields::CreateDefault<SooEnabled()>(), 
        hasher{},key_equal{}, CharAlloc{}
      };
};
```

The tuple's first element `CommonFields` holds those fields in a `raw_hash_set` that do not depend on the template parameters, and therefore, can be passed conveniently to helper functions. It has two member fields:

```cpp
class CommonFields{
  // ...
  HashtableInlineData inline_data_;

  // Either the heap pointer or the SOO slot.
  HeapOrSoo heap_or_soo_;
}
```

The control-bytes array and the main array containing the elements of the `flat_hash_set` reside in a single contigous block of memory allocated dynamically on the heap. If the elements are small enough, they can be stored on the stack using SOO. `HeapOrSoo` is a C-style union of two alternatives: 1) a field `heap` which contains the memory address of the blob of memory holding the control-bytes array and the main array 2) a byte-array `soo_data`.

```{.cpp include="./raw_hash_set.h" start-line=1238 end-line=1254 code-line-numbers="true" filename="absl/container/internal/raw_hash_set.h"}
```

The `HeapPtrs` is just a wrapper over a pointer to a byte-array.

```{.cpp include="./raw_hash_set.h" start-line=1222 end-line=1231 code-line-numbers="true" filename="absl/container/internal/raw_hash_set.h"}
```
# The control bytes array

As I mentioned earlier, we keep a little parallel array of metadata. What do we need to keep in the meta-data array? We need to know, if a slot in the main array is empty, whether it's full or whether it's deleted. What the implementation does is something very clever. 

```{.cpp include="./hashtable_control_bytes.h" start-line=170 end-line=189 code-line-numbers="true" filename="absl/container/internal/hashtable_control_bytes.h"}
```

The control byte array is an array of `ctrl_t`. If a slot in the main array of elements is empty or deleted, it corresponding control byte has its high-bit (MSB) = `1`. IF its empty, the control byte is `0b1000 0000` or `0x80`. If its deleted, the control byte is `0b1111 1110` (the 2s complement of `0b1000 000`) or `0xFE`. If the slot of the main array is full (occupied), the control byte has its high-bit = `0`. 

Now, the hash function produces a `64`-bit hash value. We split this value into two parts: 

- `H1`, a `57`-bit hash value, which is used to identify the element index within the table itself, which is truncated and modulated as any normal hash value.

- `H2`, the remaining `7`-bits, used to store metadata for this element. The `H2` bits are stored in the control byte array. 

```{python}
# | code-fold: true
# | code-summary: "Show the code"
#| fig-cap: "The hash value split into two parts: H1 and H2"
%%itikz --temp-dir --tex-packages=tikz,color --tikz-libraries=arrows.meta --implicit-standalone
\begin{tikzpicture}[scale=2.5]
  \pagecolor{white}
  \draw[fill=lime, thick, yscale=1.5] (6.16,3) rectangle (6.93,3.25);
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (6.14,3) rectangle (6.28,3.25);
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (0,3) rectangle (0.77,3.25);
  \node[draw=none, node font=\ttfamily] at (0.39,4.69) {0011 0110};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (0.77,3) rectangle (1.54,3.25);
  \node[draw=none, node font=\ttfamily] at (1.13,4.69) {1101 1011};
  \node[draw=none, node font=\ttfamily] at (6.51,4.69) {1000 1110};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (1.54,3) rectangle (2.31,3.25);
  \node[draw=none, node font=\ttfamily] at (1.9,4.65) {...};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (2.31,3) rectangle (3.08,3.25);
  \node[draw=none, node font=\ttfamily] at (2.71,4.65) {...};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (3.08,3) rectangle (3.85,3.25);
  \node[draw=none, node font=\ttfamily] at (3.48,4.65) {...};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (3.85,3) rectangle (4.62,3.25);
  \node[draw=none, node font=\ttfamily] at (4.22,4.67) {...};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (4.62,3) rectangle (5.39,3.25);
  \node[draw=none, node font=\ttfamily] at (4.99,4.68) {...};
  \draw[fill=cyan!64!magenta!51, thick, yscale=1.5] (5.39,3) rectangle (6.16,3.25);
  \node[draw=none, node font=\ttfamily] at (5.76,4.68) {...};
  \node[draw=none, node font=\itshape, minimum width=72pt] (node1) at (3.23,5.39) {H1 (57-bits)};
  \node[draw=none, node font=\itshape, minimum width=72pt] (node2) at (6.6,5.39) {H2 (7-bits)};
  \draw[arrows=Triangle-Triangle, yscale=1.5] (0.01,3.46) -- (6.28,3.44);
  \draw[arrows=Triangle-Triangle, yscale=1.5] (6.28,3.44) -- (6.93,3.44);
\end{tikzpicture}
```

